### ISSUE TITLE
Not receiving private message event?

### ISSUE THREAD

**Issue by daveoon** [Rantanen/node-mumble#112]
I listen to onMessage event but i never get private message, only channel message, is there something i did wrongly or setup?
```
mClient.on('message', (message, user, scope) => util.log(`Message ${scope} => ${user.session}:${user.name} "${message}"`))
```

**Comment by Rantanen** [comment]
Didn't have time to spin up my test environment over the weekend. Just tried this now though - running the `examples/wrapper.js` and sending a private message to the user over the Mumble client. The script reacted to this just fine.

The code the example uses to do this is: https://github.com/Rantanen/node-mumble/blob/master/examples/wrapper.js#L97-L104

This _could_ have something to do with registered users vs unregistered users. Although looking at the code I don't believe this should affect the things.

**Comment by daveoon** [comment]
@Rantanen hi, thanks for the reply. sorry for the confusion as i was trying to see if i can listen to private message send between users. seems like the api is meant for group and personal private message. in this case, is there anyway to achieve evesdropping other users private messages? i will also try to play around with protobuf so that I can understand the relevant features. So far, i am only familiar with ICE but facing an issue with callback on nodejs.

**Comment by Rantanen** [comment]
node-mumble is a Mumble _client_ library. As such the library interfaces with Mumble server just like any other Mumble client, such as the official one. Mumble server does not provide a way for Mumble client to eavesdrop on user's private messages. You'll need something server-side, such as ICE for this.

**Comment by daveoon** [comment]
@Rantanen thank you for the information. i have just fork this repo and will keep you posted when there is any pull request.
