### ISSUE TITLE
Not recording from subgroup.

### ISSUE THREAD

**Issue by djromy2006** [Rantanen/node-mumble#121]
I have the app installed and I am able to record at the root level of mumble 1.3.2; however, when a user is in the child folder, the recording doesn't happen anymore. Do you know I could set it up to record at all level? 
When I see the log, there is no voice recording data when the user is within a subdirectory but if I move a user from one group to other, it will log the transaction but will not record voice if a user is outside the root directory.

**Comment by Rantanen** [comment]
`node-mumble` is a client library, so it can only act as a Mumble client. Murmur limits the audio data to the clients within the channel (or linked channels). To be able to receive audio data from non-root channels, the `node-mumble` application needs to join that channel.
