### ISSUE TITLE
OutputStreams always emitting zeros

### ISSUE THREAD

**Issue by Prior99** [Rantanen/node-mumble#23]
They should not emit forever. If there is no input, they should not emit.

**Comment by Prior99** [comment]
Is there a reason to do this?
I see this is done on purpose here:


        // If we're overdue on written frames, write an empty frame.
        if( this.writtenUntil + this.connection.FRAME_LENGTH < Date.now() ) {
            this.push( this.emptyFrame );
            this.writtenUntil += this.connection.FRAME_LENGTH;
            return;
        }

What is the purpose of this?

**Comment by Rantanen** [comment]
I think this was done for the case where the stream is piped to a file as is. So the moments where the user is silent will be recorded as silence in the output file.

Two options:

- Parameter to `getOutputStream` (or `userOutputStream` or whatver the method name is) so the invoker can specify whether they want silence to count as no frames or zero-frames.
- `voice-start` event has an output stream as a parameter that includes audio only from the current voice-session and then `end`s.

**Comment by Rantanen** [comment]
(Of course we could do both)

**Comment by Prior99** [comment]
Do you want the default behaviour to be writing empty frames or not to?
If we change the default behaviour we could break things for people..

I assume you want to obtain the current behaviour as default.

**Comment by Rantanen** [comment]
Yeah, think so.  No idea what would be the better default, but for backwards compatibility I think we should keep the current as default.
