### ISSUE TITLE
opus support?

### ISSUE THREAD

**Issue by jamon** [Rantanen/node-mumble#3]
I'm not sure how different the libopus library is from libcelt, and not sure how difficult it'd be to build a node-opus.  Unfortunately I don't have the background to really contribute much to this, short of testing and Node.JS side code, but I at least wanted to express my interest, in case you had free time and interest in updating :)

Thanks!

**Comment by Rantanen** [comment]
I would imagine it's not too difficult to use and given opus is part of WebRTC a node-opus library will happen sooner or later. I'm finally back from a year-long government commitment and picking these projects up.

Currently trying to get [Rantanen/node-peerconnection](http://github.com/Rantanen/node-peerconnection) working again for WebRTC. Given this will require opus encoding at some point, I'll probably get around to it then.

**Comment by Prior99** [comment]
Bump! Opus support would be a big plus. Maybe you can take a look at it using your own node-opus @Rantanen ? If you don't have the time or are to busy I could also take a look at this but I guess you could do it better and faster.

**Comment by Rantanen** [comment]
Planned on taking a look at it this evening once I finish my real work for the day.

**Comment by Rantanen** [comment]
Implemented in 47a6be94fddb97d13b831ec18505e13010b62f25

Thanks to @Prior99 for starting the work!
