### ISSUE TITLE
Rename MumbleWrapper to MumbleClient maybe?

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/node-mumble#31]
While `MumbleWrapper` makes sense from the internal point of view, now that the name is exposed to the users through documentation, etc. I think we should rename it to `MumbleClient` as wrapper might end up confusing the users?

This shouldn't affect the interfaces in any way so it's not as big of a change as it sounds like.

Thoughts?

**Comment by Prior99** [comment]
+1

**Comment by Rantanen** [comment]
That's enough for me. Done. :)
