### ISSUE TITLE
Run this

### ISSUE THREAD

**Issue by robotrono** [Rantanen/node-mumble#34]
Well im new user with node js, how can I run this client on node js? Im have installed node js and python. 

I get this:

```
D:\mumble\web>node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'bindings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\mumble\web\node_modules\jitterbuffer\index.js:2:20
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

**Comment by Prior99** [comment]
1. I recommend you read a tutorial about node.js first
 2. This is not a client but a library which could be used to created bots on top of it
 3. You need to install the dependencies. ```npm install``` in the projects root direcrory should help you. Try ```npm install --python=python2``` if you experience problems with node-gyp and python 3.
 4. You do not want to run index.js, try one of the examples instead.

**Comment by Rantanen** [comment]
Also you'll need to sort out the build chain for `node-jitterbuffer`, `node-celt` and `node-opus`. I don't think those have Windows build configs at the moment.

**Comment by Rantanen** [comment]
Windows support done! So now it can be used there. The easiest way to confirm it on Windows is probably running the following commands:

```
git clone https://github.com/Rantanen/node-mumble
cd node-mumble
npm install
set MUMBLE_URL=your.mumble.address
node examples/sin.js
```

Although for actual usage you'll want to create your Node application and then do `npm install mumble`.

**Comment by Prior99** [comment]
Very nice.

**Comment by Rantanen** [comment]
I'm going to close this for now as based on this there's nothing we can do.

If @robotrono still has problems running this in Windows, re-open it.
