### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by Erbj** [Rantanen/node-mumble#42]
For some reason I can't install the module via: npm install mumble

npm gives me the following error:

npm ERR! Error: ENOENT, open 'C:\Users\myuser\node_modules\mumble\qgit push'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mumble"
npm ERR! cwd C:\Users\myuser
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\myuser\node_modules\mumble\qgit push
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\myuser\npm-debug.log
npm ERR! not ok code 0

Help would be appreciated. Thank you.

**Comment by Rantanen** [comment]
Should be fixed. I had published the NPM version from a bad computer that contained some garbage in the project folder. Should work fine now.
