### ISSUE TITLE
How do I create a channel and join it?

### ISSUE THREAD

**Issue by justinmchase** [Rantanen/node-mumble#45]
I'm looking for something like:

    var name = 'testing'
    client.createChannel(name)
    client.on('channel-create', function (channel) {
        if(channel.name === name) {
          client.channel.join(channel)
        }
    })

**Comment by Rantanen** [comment]
Previously this required `client.connection.sendMessage` usage to send the protobuf messages. Now there is an API for this:

```
var parent = client.getChannelByName( 'My Channel' );
parent.addSubChannel( 'New channel' );
client.on( 'channel-create', function( channel ) {
  // ...
});
```

**Comment by Rantanen** [comment]
(And yes. You still need the channel.name === name, etc.)

**Comment by justinmchase** [comment]
Perfect thanks! Can I get the root via `getChannelByName( null )` ? Or is it just hanging off of client?

**Comment by Rantanen** [comment]
I'd say use `client.rootChannel` or maybe `getChannelByName( 'Root' )`. I'm just assuming root channel is reported with the name of "Root" by the server.

**Comment by justinmchase** [comment]
I think it's null, I'll figure it out. Thanks.
