### ISSUE TITLE
Static noise when trying to stream audio.

### ISSUE THREAD

**Issue by 96AA48** [Rantanen/node-mumble#5]
I'm having problems streaming audio data to a server.
Whenever I fully decode a mp3 into a writeable stream and then encode it, it results into a static noise on the server. 
I tried this with the opus codec, CELT codec, WAVE codec and raw PCM data. None of them seem to work. I also tried creating a readable stream from a CELT encoded file straight to the connection.inputStream(), it had the same result.

I could use some help!

**Comment by Rantanen** [comment]
The mumble-web streams eat raw PCM data. Static noise usually means a decoding/encoding problem. You should try playing the encoded data with something else (ALSA's speaker-test should work). See that it is in proper 16-bit LE PCM format.

(Also sorry for the late answers. Had a year-long government commitment that had me away)
