### ISSUE TITLE
user.id is undefined

### ISSUE THREAD

**Issue by Prior99** [Rantanen/node-mumble#53]
user.id is undefined even when user is registered to the server.

**Comment by Prior99** [comment]
Both this issue as #52 seem to have been introduced between 02a79891f8d01f3128faf619a5a9f38320d65ec0 and bb10245a3694cf0d8b1adfc6c42df965f2a5b8c3

**Comment by Prior99** [comment]
This as well as #52 have been introduced by using a new library for protobuf. It creates the properties with udnerscores instead of camlecase. This also introduced numerous other issues and missing properties. I will see whether I can find and fix them all.

**Comment by Rantanen** [comment]
PR merged
