### ISSUE TITLE
Audio capture and playback

### ISSUE THREAD

**Issue by justinmchase** [Rantanen/node-mumble#57]
I created a new project compatible with node-mumble, specifically to live stream captured microphone data and playback what comes from the server. It's not super robust yet but I plan on adding mac builds and pre-built binaries in the near future. It uses openal to capture and playback the audio and seems to perform quite well. 

I was previously attempting to use html5 web audio apis in electron but they are, frankly, not good enough. Either in stability or performance, I'm not sure. But this works like a champ so there it is :)

Project: [node-mumble-audio](http://github.com/EvolveLabs/node-mumble-audio.git)

Example code to work with `node-mumble`:
```
var audio = require('./index');
var mumble = require('electron-mumble');
var speaker = new audio.PlaybackDevice();
var source = new audio.CaptureDevice();
var out_stream = null;

console.log( 'Connecting...' );
mumble.connect( process.env.MUMBLE_SERVER, {}, function ( error, connection ) {
    if( error ) { throw new Error( error ); }

    console.log( 'Connected.' );
    console.log( 'Authenticating...' );

    out_stream = connection.inputStream({sampleRate: 48000});

    connection.authenticate( process.env.MUMBLE_USER, process.env.MUMBLE_PASS );
    connection.on( 'initialized', onInit );
    connection.on( 'voice', onVoice );
});

var onInit = function() {
    console.log( 'Authenticated.' );

    source.on('data', function (data) {
    	out_stream.write(data);
    })
    source.start();

    // Connection is authenticated and usable.
    speaker.play();
};

var onVoice = function( pcmData ) {
    speaker.write(pcmData);
}
```

Enjoy, and that is all :)

**Comment by Prior99** [comment]
Thanks for the notice but as this is not a real issue I recommend closing this issue.

Maybe we can mention projects utilizing node-mumble in the README.md?

I suggest adding this to the examples.

**Comment by justinmchase** [comment]
I think there is a label for info but I can't edit them. But yes not an issue, I'll close it.

**Comment by Rantanen** [comment]
Including these at the end of the readme sounds good!
