### ISSUE TITLE
MumbleClient.users() not returning users online

### ISSUE THREAD

**Issue by tjhorner** [Rantanen/node-mumble#70]
`MumbleClient#users()` doesn't return the list of users currently online, rather all users that have been on the server when the client has been connected regardless if the user is offline or online.

**Comment by Prior99** [comment]
Maybe add a MumbleClient.usersOnline() and MumbleClient.usersOffline() method as well as a property "online" to the user objects instead of changing the behaviour of this method?

**Comment by tjhorner** [comment]
>Maybe add a MumbleClient.usersOnline() and MumbleClient.usersOffline() method as well as a property "online" to the user objects instead of changing the behaviour of this method?

Yes, this seems like the best solution instead of making breaking changes.

**Comment by Rantanen** [comment]
In terms of keeping the API clean and logical, I wouldn't consider this breaking change. The session IDs, etc. are wrong anyway for disconnected users. If the application needs to keep track of all the possible users, they should persist them somewhere.

.. and how did I miss the original issue posted October 18th? This completely went past me. Sorry for that!

**Comment by Rantanen** [comment]
(I'd be okay with usersOnline() and usersOffline() if users() returned -all- the registered users from the server. Even the ones who haven't logged on at all.)

Returning users the client has seen is just iffy.

(On the other hand: While fixing this, I think we should also include a method to retrieve all registered users in case the bot account has necessary permissions for that.)

**Comment by tjhorner** [comment]
>While fixing this, I think we should also include a method to retrieve all registered users in case the bot account has necessary permissions for that.

Does a user require a special permission to view all registered users? I'm not seeing any ACL for that:


![image](https://cloud.githubusercontent.com/assets/2646487/12026771/604a6f2a-ad72-11e5-8e39-f91c1c2f81dc.png)

**Comment by Rantanen** [comment]
Not sure about that. Could be everyone can see them.

**Comment by tjhorner** [comment]
Hm, I went on a random server and I couldn't access registered users.

**Comment by Rantanen** [comment]
Could be the 'register user' permission affects it.
