### ISSUE TITLE
[QUESTION] How do I rename a channel?

### ISSUE THREAD

**Issue by theLine** [Rantanen/node-mumble#75]
I'd like to rename a channel.
Basically I'm doing this:
```js
var channel = connection.channelById(22);
channel.update({
	name: 'new Channel Name',
	linksAdd: null,
	linksRemove: null,
	parent: null,
});
```
But for some reason the channel won't update its name.

P.S.: I nulled the other properties because I got the following error:
```
TypeError: Cannot call method '_addChild' of undefined
    at EventEmitter.Channel._checkParent (path/to/node-mumble/lib/Channel.js:2
    at EventEmitter.Channel.update (path/to/node-mumble/lib/Channel.js:120:14)
```

**Comment by Rantanen** [comment]
`update()` is an internal function. It should really have been called `_update()`, but you can deduce that also from the fact that it hasn't been documented.

That function updates the local `Channel` instance based on data coming from the server - it won't alter the server state.

There is no convenience method for renaming the channel, but I believe following would work.

```javascript
client.connection.sendMessage( 'ChannelState', {
  channel_id: channel.id,
  name: 'new name'
});
```

**Comment by theLine** [comment]
Thanks for your quick response!

This worked as you said. =)
