### ISSUE TITLE
warning: jitter buffer sees negative buffering, your code might be broken.

### ISSUE THREAD

**Issue by bleachisback** [Rantanen/node-mumble#84]
This error is constantly spammed in my console after prolonged use with values that alternate randomly (usually 6 and sometimes 4). I narrowed down [where the warning is being sent from](https://github.com/zhenkai/mumble/blob/master/speex/libspeex/jitter.c#L754-L779), but since it's not an error and there is no stack trace, I can't tell where it's going wrong. I've tried debugging at each line where JitterBuffer is referenced, but those lines are called too often and the warning seems to come up sporadically.

**Comment by Rantanen** [comment]
Is this a new issue? If so, this might be a problem with #80.

Just in case: @Prior99

**Comment by bleachisback** [comment]
It has existed for the entire time I've used the library, but I only started using it a week ago.

**Comment by bleachisback** [comment]
Actually I updated and have been running it for a while now and it seems to have been fixed.

**Comment by Prior99** [comment]
This is relates to an oudated version of node-jitterbuffer. I had a similiar problem months ago which was fixed in node-jitterbuffer.
