### ISSUE TITLE
Install error 886 verbose stack Error: celt@0.1.9 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by funkyoself** [Rantanen/node-mumble#91]
```
886 verbose stack Error: celt@0.1.9 install: `node-gyp rebuild`
886 verbose stack Exit status 1
886 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
886 verbose stack     at emitTwo (events.js:106:13)
886 verbose stack     at EventEmitter.emit (events.js:191:7)
886 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
886 verbose stack     at emitTwo (events.js:106:13)
886 verbose stack     at ChildProcess.emit (events.js:191:7)
886 verbose stack     at maybeClose (internal/child_process.js:852:16)
886 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
887 verbose pkgid celt@0.1.9
888 verbose cwd /home/marcin/Workspace/mumble
889 error Linux 4.5.0-2-amd64
890 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "mumble" "--save"
891 error node v6.2.1
892 error npm  v3.8.0
893 error code ELIFECYCLE
894 error celt@0.1.9 install: `node-gyp rebuild`
894 error Exit status 1
895 error Failed at the celt@0.1.9 install script 'node-gyp rebuild'.
895 error Make sure you have the latest version of node.js and npm installed.
895 error If you do, this is most likely a problem with the celt package,
895 error not with npm itself.
895 error Tell the author that this fails on your system:
895 error     node-gyp rebuild
895 error You can get information on how to open an issue for this project with:
895 error     npm bugs celt
895 error Or if that isn't available, you can get their info via:
895 error     npm owner ls celt
895 error There is likely additional logging output above.
896 verbose exit [ 1, true ]
```

node v6.2.1
npm v3.8.0

**Comment by Rantanen** [comment]
nan required update. Pushed 0.1.10 to NPM. Should compile now.

**Comment by jonabasque** [comment]
I think i have the same problem.

debian 8.10
node 6.10.3 LTS with NVM

> ref@1.3.4 install /home/mumble/node_modules/ref
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.35-1-pve
gyp ERR! command "/home/mumble/.nvm/versions/node/v6.10.3/bin/node" "/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mumble/node_modules/ref
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> celt@0.1.11 install /home/mumble/node_modules/celt
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.35-1-pve
gyp ERR! command "/home/mumble/.nvm/versions/node/v6.10.3/bin/node" "/home/mumble/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mumble/node_modules/celt
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/home/mumble
+-- jitterbuffer@0.1.12 
+-- node-opus@0.2.6 
| +-- bindings@1.2.1 
| `-- nan@2.4.0 
`-- protobufjs@4.1.3 
  +-- ascli@1.0.1 
  | +-- colour@0.7.1 
  | `-- optjs@3.2.2 
  +-- bytebuffer@4.1.0 
  | +-- bufferview@1.0.1 
  | `-- long@2.4.0 
  +-- glob@5.0.15 
  | +-- inflight@1.0.6 
  | | `-- wrappy@1.0.2 
  | +-- inherits@2.0.3 
  | +-- minimatch@3.0.4 
  | | `-- brace-expansion@1.1.7 
  | |   +-- balanced-match@0.4.2 
  | |   `-- concat-map@0.0.1 
  | +-- once@1.4.0 
  | `-- path-is-absolute@1.0.1 
  `-- yargs@3.32.0 
    +-- camelcase@2.1.1 
    +-- cliui@3.2.0 
    | +-- strip-ansi@3.0.1 
    | | `-- ansi-regex@2.1.1 
    | `-- wrap-ansi@2.1.0 
    +-- decamelize@1.2.0 
    +-- os-locale@1.4.0 
    | `-- lcid@1.0.0 
    |   `-- invert-kv@1.0.0 
    +-- string-width@1.0.2 
    | +-- code-point-at@1.1.0 
    | `-- is-fullwidth-code-point@1.0.0 
    |   `-- number-is-nan@1.0.1 
    +-- window-size@0.1.4 
    `-- y18n@3.2.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/mumble/package.json'
npm WARN mumble No description
npm WARN mumble No repository field.
npm WARN mumble No README data
npm WARN mumble No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.35-1-pve
npm ERR! argv "/home/mumble/.nvm/versions/node/v6.10.3/bin/node" "/home/mumble/.nvm/versions/node/v6.10.3/bin/npm" "install" "mumble"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! celt@0.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the celt@0.1.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the celt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs celt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls celt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mumble/npm-debug.log
