### ISSUE TITLE
How do I set the comment for the connected user?

### ISSUE THREAD

**Issue by rymate1234** [Rantanen/node-mumble#93]
I had a look at the code of the project, and there seems to be no way to set the comment of the user connected with node-mumble.

How would I go about doing this?

**Comment by tjhorner** [comment]
I haven't tested this, but this should probably work:

```javascript
client.connection.sendMessage( 'UserState', { session: client.user.session, actor: client.user.session, comment: "the comment of the user" } );
```

Where `client` is your `MumbleClient` instance. I can send a pull request to make this easier, if you'd like :)

**Comment by tjhorner** [comment]
Also note that if you want to _get_ a user's comment, it's slightly more complicated. You'd need to check if `comment_hash` exists, then send a `RequestBlob` [with the user's session](https://github.com/Rantanen/node-mumble/blob/master/lib/Mumble.proto#L510-L517) and then respond to the new `UserState` accordingly.

**Comment by rymate1234** [comment]
That code worked perfectly, thanks!

**Comment by tjhorner** [comment]
I made a PR (#94) so you'll soon be able to use `User.setComment`

**Comment by rymate1234** [comment]
Thanks! Probably will help the next person who wants to set a comment :)
