### ISSUE TITLE
Fatal error in api.cc

### ISSUE THREAD

**Issue by idietmoran** [Rantanen/node-mumble#95]
```
#
# Fatal error in api.cc, line 1051
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

        v8::Testing::DeoptimizeAll [0x00007FF7DB5ED146+1835798]
        v8::Template::Set [0x00007FF7DB3FB733+387]
        NodeJitterBuffer::Init [0x00007FFD68DC2282+258] (d:\github\simp-bot-test\node_modules\jitterbuffer\src\node-jitt
erbuffer.cc:142)
        NodeInit [0x00007FFD68DC2529+9] (d:\github\simp-bot-test\node_modules\jitterbuffer\src\node-jitterbuffer.cc:167)
        node_module_register [0x00007FF7DAE66C17+2439]
        v8::Isolate::NumberOfHeapSpaces [0x00007FF7DB3F6A0F+3076927]
        v8::Isolate::NumberOfHeapSpaces [0x00007FF7DB39647E+2682286]
        v8::Isolate::NumberOfHeapSpaces [0x00007FF7DB395373+2677923]
        v8::Isolate::NumberOfHeapSpaces [0x00007FF7DB39522E+2677598]
        (No symbol) [0x00000086E4A063AB]
```

I'm not sure if this is something that broke in newer versions of node / npm installs, but I've been getting this error constantly.

**Comment by Rantanen** [comment]
I'll take a look at this in the evening.

**Comment by idietmoran** [comment]
Thank you. This occurred on 7.0.0.

I want to avoid rolling back the node version on my server is possible.

**Comment by Rantanen** [comment]
I know node-jitterbuffer had some deprecation warning a while back, but when I tried debugging that I had trouble getting the thing to compile in my environment. No idea what caused that - then I forgot about it.

The stack fortunately has the line numbers for node-jitterbuffer so I'll take a look at how to fix that. I'm guessing that's the reason this is happening now.

**Comment by Rantanen** [comment]
Found the issue in node-jitterbuffer. Fixed it there (and in node-celt).

**Comment by idietmoran** [comment]
working now, thanks you're awesome.

**Comment by Rantanen** [comment]
I might disagree with that given Node started warning about this in 6.0.0 and it was reported in August by notthetup in #92 but I never got around fixing it until it broke.

But I'm glad someone thinks that way. Thanks! :)
